-- DROP DATABASE
DROP DATABASE IF EXISTS memeSite_db;

-- CREATE DATABASE
CREATE DATABASE memeSite_db;

-- USE DATABASE
USE memeSite_db;

-- User Table

CREATE TABLE username (
    id INT NOT NULL AUTO_INCREMENT,
    username VARCHAR(40) NOT NULL UNIQUE,
    password VARCHAR(200) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
)

-- Post Table

CREATE TABLE post (
    id INT NOT NULL AUTO_INCREMENT,
    caption VARCHAR(500) NOT NULL,
    user_id INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE CASCADE
)

-- Comment Table

CREATE TABLE comment (
    id INT NOT NULL AUTO_INCREMENT,
    comment_content TEXT NOT NULL,
    post_id INT NOT NULL,
    user_id INT NOT NULL,
    create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    FOREIGN KEY (post_id) REFERENCES post(id) ON DELETE CASCADE,
    FOREIGN KEY (username_id) REFERENCES username(id) ON DELETE CASCADE
)